### ISSUE TITLE
System freeze while phone connect

### ISSUE THREAD

**Issue by YoungNFoolish** [M0Rf30/android-udev-rules#110]
Hi,
I installed your repository hours ago. My problem is that the system freeze for 15~20 secs while i connect phone to laptop for debugging an app.
I'm using Fedora 25 on my laptop and my phone is Huawei P9 Lite running EMUI 5.0. 
Any kind of help will be appreciated.

sorry for my bad English
Regards

**Comment by M0Rf30** [comment]
please send me a "dmesg -w > log" output in order to figure out
