### ISSUE TITLE
Nexus 5X problem

### ISSUE THREAD

**Issue by Pitel** [M0Rf30/android-udev-rules#112]
Commit: 65421ca0be0a8c5950af7c821f65d47066ffa093 (and also some previous)

After every boot of Ubuntu 17.04 I have to run `sudo service udev reload`, otherwise my Nexus 5X is not recognized. Other phones are ok.

```
adb devices
List of devices attached
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
00f563b073ba1176	no permissions (verify udev rules); see [http://developer.android.com/tools/device.html]

sudo service udev reload
//also reconnects phone

adb devices
00f563b073ba1176	device
```

**Comment by mmartin101** [comment]
having the same issue :cry:

**Comment by mmartin101** [comment]
@Pitel This worked for me:
Instead of creating a symlink like the README suggests, just copy 51-android.rules to /etc/udev/rules.d (make sure to use sudo). Then reboot your machine and it should work.

**Comment by M0Rf30** [comment]
@Pitel @mmartin101. Updated README.md. Now it should work
