### ISSUE TITLE
Add support sysusers.d systemd file

### ISSUE THREAD

**Issue by anatol** [M0Rf30/android-udev-rules#133]
Instead of asking users to create `adbusers` group manually we should use standard facility provided by `systemd`. There is `sysusers` https://www.freedesktop.org/software/systemd/man/sysusers.d.html  please add a config file for it.

**Comment by M0Rf30** [comment]
Added in da35e0345cfe50e45dcc6c8d6d841c71117cf899
Thanks 💃
