### ISSUE TITLE
sudo systemd-sysusers does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by NYCJacob** [M0Rf30/android-udev-rules#136]
this line did not work on my machine running Ubuntu 16.04.
can I just add adbusers using groupadd ?

**Comment by M0Rf30** [comment]
Yes you can use the old method. Is systemd-sysusers  in systemd package?
https://packages.ubuntu.com/search?searchon=contents&keywords=systemd-sysusers&mode=exactfilename&suite=artful&arch=any

**Comment by NYCJacob** [comment]
hmm that link doesn't seem to show what exactly the old method is, excuse my ignorance

**Comment by M0Rf30** [comment]
### Add adbusers group
sudo groupadd adbusers
 ### Add your user to the adbusers group
sudo usermod -a -G adbusers $(whoami)

**Comment by NYCJacob** [comment]
yea I did that already and my device is still not recognized
