### ISSUE TITLE
sudo systemd-sysusers ko on ubuntu 16

### ISSUE THREAD

**Issue by bodtx** [M0Rf30/android-udev-rules#139]
systemd-sysusers appears to not being here on ubuntu 16

maybe raplace command with a simple

`sudo groupadd adbusers`

**Comment by zamber** [comment]
Thanks for the feedback. Can you do a PR then? Specify which Ubuntu version
hasn't got systemd and suggest your fix for these and leave the one with
systemd-sysusers for newer ones.

**Comment by bodtx** [comment]
you mean on the README.md ?

**Comment by zamber** [comment]
Yes :).
