### ISSUE TITLE
Add Samsung Galaxy S9

### ISSUE THREAD

**Issue by AmiraAlex** [M0Rf30/android-udev-rules#142]
It looks like this new device is not recognized by the current udev rules.
I grabbed some `lsusb` info for you, in normal mode & then in download mode:

```
Bus 001 Device 009: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy (MTP)
Bus 001 Device 008: ID 04e8:685d Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II] (Download mode)
```

Is this the information you need? If not, let me know how I can help :)

**Comment by M0Rf30** [comment]
These value are just present in udev respectively for MTP(try with packages that use libmtp like gvfs-mtp if you use gnome ) and Normal mode. Could you try to put in ADB mode and send lsusb output?
