### ISSUE TITLE
Use interface ID instead of vendor/product IDs

### ISSUE THREAD

**Issue by ktnr74** [M0Rf30/android-udev-rules#147]
Instead of trying to match all those different devices by different vendors do what adb does itself: look for the interface IDs (class/subclass/protocol), which in case of adb always will be 0xFF4201, and in case of fastboot will be 0xFF4203.

So all those rules can be replaced by a single line:
http://ktnr74.blogspot.com/2014/09/the-most-comprehensive-write-up-on-how.html

Also Google has removed the vendor ID whitelist a few years back, so adb_usb.ini is no longer used - you can remove the README footnote.

**Comment by M0Rf30** [comment]
I added the universal rule at the beginning of the rules, if the check of interfaces fails, the other rules will follow. Let me know what do you think

**Comment by ktnr74** [comment]
the simplified version of the rules file I use on my development system is similar to this
https://gist.github.com/ktnr74/f749a4bc2aa13b190b46a8643d1b465d

The main difference between the approaches is that my rule would only set devices permissions if either adb or fastboot interface is enumerated regardless of the vendor ID. If some users relied on the vendor ID based rules to provide access to PTP/MTP/UMS/etc interfaces - those interfaces would have to be added separately. Or the users could just keep using the vendor based rules.
