### ISSUE TITLE
Need to add user to the 'audio' group for my phone to be detected in ADB.

### ISSUE THREAD

**Issue by DeviousPenguin** [M0Rf30/android-udev-rules#150]
Not a huge issue, but rather odd and I'm not sure why this is happening.

I followed the instructions in the README on Lubuntu 18.04 minimal install.

After reboot it seems my phone is added to the 'audio' group.

    > lsusb
    Bus 001 Device 006: ID 1bbb:0167 T & A Mobile Phones 

    > ls /dev/bus/usb/001/006 -la
    crw-rw----+ 1 root audio 189, 5 Aug  5 18:40 /dev/bus/usb/001/006

If anyone else has this same issue, adding your user to the 'audio' group allows adb to see the phone:

    > adb devices
    List of devices attached

    > sudo usermod -a -G audio (username)

Make sure you put your own username in, $(whoami) may not work due to sudo.
Now exit from session, log out and in, new session:

    > adb devices
    List of devices attached
    0123456789ABCDEF        device

I'm not sure how my phone ended up in the audio group, it could be a bug with Ubuntu, but it works now.

**Comment by M0Rf30** [comment]
This is caused by an Ubuntu patch for libmtp rules that adds audio group.
Your device (Alcatel/TCT 6010D/TCL S950) is detected also as mtp device and thats why you have to satisfy this requirement.
