### ISSUE TITLE
adb universal rule breaks adb connection to HTC One X (endeavoru)

### ISSUE THREAD

**Issue by bbo2adwuff** [M0Rf30/android-udev-rules#154]
I have a [HTC One X (endeavoru)](https://en.wikipedia.org/wiki/HTC_One_X), and until now adb always worked fine. But after commit https://github.com/M0Rf30/android-udev-rules/commit/704f83d8528a56c969dab8a9b63bf83279d4c71b I just get:

```
adb shell
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found
```
When commenting out the lines https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules#L8-L11 I get `* daemon started successfully`.

**Comment by M0Rf30** [comment]
Please try with latest commit https://github.com/M0Rf30/android-udev-rules/commit/c8f2e1e4958abe5238245c79c071b91aa8ae50a3
If doesn't work send me the output of `journalctl -p 3 -xb`

**Comment by bbo2adwuff** [comment]
Oh sorry I forgot to mention that I use 20181030, so fix for https://github.com/M0Rf30/android-udev-rules/issues/153 is already included.

`journalctl -p 3 -xb` with 20181030 returns nothing and `journalctl -p 3 -xb` with 20181026 returns `systemd-udevd[258]: Specified group 'plugdev' unknown`.

But under both I get `error: no devices/emulators found` in the shell.

**Comment by M0Rf30** [comment]
Can you send me the output of `udevadm info -e` with attached device?

**Comment by M0Rf30** [comment]
I think that now is fixed. let me know

**Comment by bbo2adwuff** [comment]
Sorry for the late reply, I was travelling back home. 

Yes, it works with the last commit! Thanks!
