### ISSUE TITLE
Add rule for Xiaomi Redmi 8 Pro

### ISSUE THREAD

**Issue by miguelromero2000** [M0Rf30/android-udev-rules#192]
```
# RedMi 8 Pro
ATTR{idProduct}=="ff48", SYMLINK+="android_adb"
```

**Comment by JoesCat** [comment]
Hi Miguel,
Is this code for debug mode? if yes, might as well use adb_adb to include the android_adb symlink too.
```c
# RedMi 8 Pro
ATTR{idVendor}=="????", ATTR{idProduct}=="ff48", SYMLINK+="adb_adb"
```
 Can you also provide the idVendor code too (shown above as ????), this will avoid overlapping other devices from other vendors which may use the same code for a different purpose.
lsusb -v
can show you the different codes as you enable or disable debug mode.

**Comment by JoesCat** [comment]
disregard last question - gotit now. My error.

**Comment by JoesCat** [comment]
Thanks for your contribution - much appreciated!
