### ISSUE TITLE
What's the purpose of this repository?

### ISSUE THREAD

**Issue by bluraygun** [M0Rf30/android-udev-rules#200]
Just asking, https://developer.android.com/studio/run/device#setting-up describes a more simple answer.

**Comment by M0Rf30** [comment]
To properly answer:
* A little bit of [udev](https://en.wikipedia.org/wiki/Udev)

![image](https://user-images.githubusercontent.com/491117/101269525-f36f7e80-376f-11eb-8684-1d388db6c484.png)
The purpose of this repo is to collect udev rules for different Android devices and alllow a plug & play connection between your Linux box and them.
