### ISSUE TITLE
Systemd catches up with bind events

### ISSUE THREAD

**Issue by munix9** [M0Rf30/android-udev-rules#204]
The following has been researched and tested under openSUSE Tumbleweed 20210305.

I found the following interesting article on the net:
Systemd catches up with bind events https://lwn.net/Articles/837033/

When testing with `51-android.rules` in version 20210302 I found out that the `add` ACTION causes the corresponding LINKS `/dev/android` and `/dev/android_adb` to be created in the first step, but shortly after that a `bind` is done by `systemd-udevd`, which is skipped by `51-android.rules` and (probably) causes `73-seat-late.rules` to delete the LINKS as obsolete again.
```
3-2:1.3: Device (SEQNUM=3712, ACTION=add) is queued
...
3-2: /usr/lib/udev/rules.d/51-android.rules:545 LINK 'android_adb'
3-2: /usr/lib/udev/rules.d/51-android.rules:549 LINK 'android_adb'
3-2: /usr/lib/udev/rules.d/51-android.rules:729 GROUP 447
3-2: /usr/lib/udev/rules.d/51-android.rules:729 MODE 0660
3-2: /usr/lib/udev/rules.d/51-android.rules:729 LINK 'android'
...
3-2: Processing device (SEQNUM=3705, ACTION=bind)
3-2:1.3: SEQNUM=3712 blocked by SEQNUM=3705
...
3-2: /usr/lib/udev/rules.d/73-seat-late.rules:17 RUN 'uaccess'
3-2: Updating old name, '/dev/android' no longer belonging to '/devices/pci0000:...'
3-2: No reference left, removing '/dev/android'.
3-2: Updating old name, '/dev/android_adb' no longer belonging to '/devices/pci0000:...'
3-2: No reference left, removing '/dev/android_adb'.
```
So I changed `51-android.rules` accordingly:
```
--- a/51-android.rules
+++ b/51-android.rules
@@ -16,7 +16,7 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
 # Skip testing for android devices if device is not add, or usb
-ACTION!="add", GOTO="android_usb_rules_end"
+ACTION!="add", ACTION!="bind", GOTO="android_usb_rules_end"
 SUBSYSTEM!="usb", GOTO="android_usb_rules_end"
 
 # For Android devices that enable this universal rule suggested here:
```
and now it works.
Does this make sense?

**Comment by JoesCat** [comment]
What is the deviceID and VendorID for your device when it is in "developer mode"?

What is the deviceID and VendorID for your device when "developer mode" is turned off?

**Comment by munix9** [comment]
Both are the same in each case:
```
  idVendor           0x04e8 Samsung Electronics Co., Ltd
  idProduct          0x6860 Galaxy series, misc. (MTP mode)
```
What do you mean by deviceID?

**Comment by M0Rf30** [comment]
DeviceId or idProduct Is the same thing.In this case is 0x6860 for MTP mode.

**Comment by JoesCat** [comment]
Seems we have a problem if both idProduct numbers are the same (developer mode, or not).

If libmtp as well as android_rules are both attempting to grab the same device, it may make more sense that it is surrendered to mtp rules since there are far more using needing access to onboard storage vs the number of android developers that are actually developing at that exact moment in time.
If that is the case, it may be best to remove (from android rules) grabbing idProduct 6860 and letting 6860 be grabbed by libmtp.

I looked at #101 here https://github.com/M0Rf30/android-udev-rules/issues?q=is%3Aissue+6860
and seeing a long list, it may be worth using that other code at line 25:
https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules

```c
# ENV{ID_USB_INTERFACES}=="*:ff420?:*", SYMLINK+="android/$env{ID_SERIAL_SHORT}", GOTO="android_usb_rule_match"
```
modified to:
```c
ENV{ID_USB_INTERFACES}=="*:ff420?:*", ENV{adb_adb}="yes", SYMLINK+="android/$env{ID_SERIAL_SHORT}", GOTO="android_usb_rule_match"
```
and also add '#' in front of lines with idProduct 6860 to avoid grabbing the connection.

Can you give that a try?

**Comment by munix9** [comment]
Thanks for your suggestion, but I want to describe the problem differently - forget about the Galaxy Tab with 04e8:6860 for now.

I got an aged Acer Iconia Tab A210 with the following ids:
```
Normal: 0502:33cc
Debug:  0502:33cb
```
In the `51-android.rules` I added the following to the Acer section:
```
# Iconia Tab A210 (33cc=normal,33cb=debug)
ATTR{idProduct}=="33cb", ENV{adb_user}="yes"
```
(if desired you can add this to the list, but there may follow a separate request for this).

As usual, the rules are always reloaded when testing or making changes:
`udevadm control --reload`

If I leave the original setting in the `51-android.rules`
`ACTION!="add", GOTO="android_usb_rules_end"`
then the described happens:
The symlinks (one or more `/dev/android*`) are created (ACTION=add) and removed shortly after (ACTION=bind).

If I change now as described the corresponding line again to
`ACTION!="add", ACTION!="bind", GOTO="android_usb_rules_end"`
the symlinks are created (ACTION=add) and then (ACTION=bind) **not** removed again.

This is actually the problem I want to point out: no permanent symlinks without considering the bind ACTION.

Some additional data:
openSUSE Tumbleweed 20210307
systemd/udev 246.10
kernel 5.11.2-1-default x86_64

**Comment by munix9** [comment]
Addendum:
If there are concerns about changing the appropriate line to include the bind ACTION, I can also create a patch just for the openSUSE package, that's no problem. Then the original remains untouched here.
I'm just a bit surprised that apparently no other distribution seems to have the problem so far - maybe because Tumbleweed is a rolling release and thus changes become noticeable earlier.
But maybe also because some local patches still suppress or filter the kernel/udev bind/unbind ACTION.

Now I have also tested it with openSUSE Leap 15.2.
The data compared to Tumbleweed:
openSUSE Leap 15.2
systemd/udev 234-lp152.31.19.1
kernel 5.3.18-lp152.66-default x86_64

For Leap 15.2, in contrast to Tumbleweed, the definition `ACTION!="bind"` is not required, but does not hurt either.
So it looks like for more recent kernel/systemd/udev packages (for openSUSE) the customization is needed.

**Comment by JoesCat** [comment]
Okay - I see the problem using Mageia8, kernel 5.10
Before including the ACTION!="bind"
```c
$ ls -l /dev/an*
lrwxrwxrwx 1 root root 15 Mar 12 00:08 /dev/android -> bus/usb/001/035
lrwxrwxrwx 1 root root 15 Mar 12 00:08 /dev/android_adb -> bus/usb/001/035
lrwxrwxrwx 1 root root 15 Mar 12 00:08 /dev/android_fastboot -> bus/usb/001/035
$ ls -l /dev/an*
ls: cannot access '/dev/an*': No such file or directory
$ ls -l /dev/an*
ls: cannot access '/dev/an*': No such file or directory
```
incorrect values, and drops out too.

and after adding ACTION!="bind" - which gives the expected behaviour:
$ ls -l /dev/an*
lrwxrwxrwx 1 root root 15 Mar 12 00:40 /dev/android -> bus/usb/001/044
$ ls -l /dev/an*
lrwxrwxrwx 1 root root 15 Mar 12 00:40 /dev/android -> bus/usb/001/044
$ ls -l /dev/an*
lrwxrwxrwx 1 root root 15 Mar 12 00:40 /dev/android -> bus/usb/001/044
```

You solved it, should be your recognition too. Can you create a patch?
(if not, then email me, so you are applied in git correctly.)

**Comment by M0Rf30** [comment]
Could you give me some feedback on the latest commit? For any trouble we wiil re-open the issue
@munix9 thanks in advance for this deep dive on udev working mechanisms. Good catch

**Comment by M0Rf30** [comment]
Could you give me some feedback on the latest commit? For any trouble we wiil re-open the issue
@munix9 thanks in advance for this deep dive on udev working mechanisms. Good catch
