### ISSUE TITLE
Umidigi F1

### ISSUE THREAD

**Issue by Mek101** [M0Rf30/android-udev-rules#206]
Would it be possible to add the Umidigi F1 to the rules?

The relative lsusb output:
```
Bus 006 Device 002: ID 0e8d:201c MediaTek Inc. F1
```

**Comment by M0Rf30** [comment]
Of course. I'll submit this in these days. If you feel brave you could try to open a pull request towards this repo

**Comment by Mek101** [comment]
Unfortunately I don't know udev rules well enough to do anything beyond a single row

**Comment by M0Rf30** [comment]
Could you test the latest commits and give me a confirmation? Thanks in advance

**Comment by Mek101** [comment]
It does

**Comment by M0Rf30** [comment]
Many thanks
