### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by munix9** [M0Rf30/android-udev-rules#214]
Is it time for a new release?
https://github.com/M0Rf30/android-udev-rules/compare/20210501...master

**Comment by JoesCat** [comment]
Hi @munix9,
When you look at the number of patches between the last release, and today, which is only one patch, I would think it doesn't justify creating a release yet.
You need to consider each release creates work downstream, and we are working with volunteers, so the less work you push on them, the happier they are.

If you look at the prior release 20210501, you'll see 4 commits between the last release and the release before that 20210425, and if you compare the release before that, you'll see even more patches from 20210302.

Please think of it as a number of significant changes from release to release, vs time between patches. :-)

**Comment by JoesCat** [comment]
If you have one or more phones to add - those will be appreciated, but if nobody steps-up to help, then, there is little reason to push a release based on little change.

**Comment by munix9** [comment]
Thanks @JoesCat, no problem.
I just got a request regarding this and wanted to ask what the status is on this.

**Comment by munix9** [comment]
Ah, it looks like he needs the entry for ZTE, or wants to test it.
He's patching it manually for now, and maybe a new item for the list will come up after that.
I'll close this for now.
