### ISSUE TITLE
samsung

### ISSUE THREAD

**Issue by salampron** [M0Rf30/android-udev-rules#219]
So i have pulling my hair out for 3 days trying to figure out how to use udev-rules to enable fast-boot or even full adb priv on my galexy s20 fe snapdragon. any help would greatly be appreciated.

**Comment by M0Rf30** [comment]
Please iterate through the different usb modes and collect the `lsusb` output. Copy paste here and I'll add to the rules after a little bit of testing, if you wanna help, of course.
You're interested in ids like this `0a5c:5842` (vendor_id:product_id).

**Comment by salampron** [comment]
Bus 002 Device 002: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy A5 (MTP)
that is off of kali linux

**Comment by M0Rf30** [comment]
You need also to reboot to download mode and adb mode. They should have other ids.

**Comment by AKotov-dev** [comment]
Hello, **M0Rf30** and **salampron**. Sorry to get into this discussion... :) I recently released an update to ArEditor-v1.5, in which I introduced, in addition to automatic device search, manual reverse search (Ctrl+F). And I decided to check the model of the device, which is discussed here. As the editor showed, - this device (04e8:6860), or rather its `ATTR{idProduct}=="6860"` are listed in the rules file twice:
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
...
#		Galaxy Nexus (GSM) (6860=mtp,adb 6864=rndis,adb 6866=ptp,adb)
==here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
ATTR{idProduct}=="6864", SYMLINK+="android_adb"
ATTR{idProduct}=="6866", SYMLINK+="android_adb"
#		Galaxy Core, Tab 10.1, i9100 S2, i9300 S3, N5100 Note (8.0), Galaxy S3 SHW-M440S 3G (Korea only)
==and here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
```
**Question:** How will **udev** behave in this case? Sorry again for interrupting the discussion. Thanks.

Sincerely,
Alex

**Comment by M0Rf30** [comment]
> Hello, **M0Rf30** and **salampron**. Sorry to get into this discussion... :) I recently released an update to ArEditor-v1.5, in which I introduced, in addition to automatic device search, manual reverse search (Ctrl+F). And I decided to check the model of the device, which is discussed here. As the editor showed, - this device (04e8:6860), or rather its `ATTR{idProduct}=="6860"` are listed in the rules file twice:
> 
> ```
> #	Samsung
> ATTR{idVendor}!="04e8", GOTO="not_Samsung"
> ...
> ...
> #		Galaxy Nexus (GSM) (6860=mtp,adb 6864=rndis,adb 6866=ptp,adb)
> ==here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
> ATTR{idProduct}=="6864", SYMLINK+="android_adb"
> ATTR{idProduct}=="6866", SYMLINK+="android_adb"
> #		Galaxy Core, Tab 10.1, i9100 S2, i9300 S3, N5100 Note (8.0), Galaxy S3 SHW-M440S 3G (Korea only)
> ==and here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
> ```
> 
> **Question:** How will **udev** behave in this case? Sorry again for interrupting the discussion. Thanks.
> 
> Sincerely, Alex
UDEV processing should be sequential and stop on the first match.
Thanks for the catch. Will remove the duplicated line.
@salampron  I'll close this ticket because of no answer in a long time from @salampron 
Regards

**Comment by M0Rf30** [comment]
> Hello, **M0Rf30** and **salampron**. Sorry to get into this discussion... :) I recently released an update to ArEditor-v1.5, in which I introduced, in addition to automatic device search, manual reverse search (Ctrl+F). And I decided to check the model of the device, which is discussed here. As the editor showed, - this device (04e8:6860), or rather its `ATTR{idProduct}=="6860"` are listed in the rules file twice:
> 
> ```
> #	Samsung
> ATTR{idVendor}!="04e8", GOTO="not_Samsung"
> ...
> ...
> #		Galaxy Nexus (GSM) (6860=mtp,adb 6864=rndis,adb 6866=ptp,adb)
> ==here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
> ATTR{idProduct}=="6864", SYMLINK+="android_adb"
> ATTR{idProduct}=="6866", SYMLINK+="android_adb"
> #		Galaxy Core, Tab 10.1, i9100 S2, i9300 S3, N5100 Note (8.0), Galaxy S3 SHW-M440S 3G (Korea only)
> ==and here==>>> ATTR{idProduct}=="6860", SYMLINK+="android_adb"
> ```
> 
> **Question:** How will **udev** behave in this case? Sorry again for interrupting the discussion. Thanks.
> 
> Sincerely, Alex
UDEV processing should be sequential and stop on the first match.
Thanks for the catch. Will remove the duplicated line.
@salampron  I'll close this ticket because of no answer in a long time from @salampron 
Regards

**Comment by AKotov-dev** [comment]
Thanks for the explanation, **M0Rf30**. I don't want to seem intrusive, but during the check of `51-android.rules`, these duplicates were also caught, in total = 9 pieces.

I decided to display all the "suspicious" duplicates first:
```
cat ./51-android.rules | grep ^ATTR{idProduct} | cut -f1 -d "," | sort | uniq -d

ATTR{idProduct}=="0c02"
ATTR{idProduct}=="0c91"
ATTR{idProduct}=="0fff"
ATTR{idProduct}=="107e"
ATTR{idProduct}=="2008"
ATTR{idProduct}=="4ee2"
ATTR{idProduct}=="4ee6"
ATTR{idProduct}=="4ee7"
ATTR{idProduct}=="61f9"
ATTR{idProduct}=="6601"
ATTR{idProduct}=="681c"
ATTR{idProduct}=="685d"
ATTR{idProduct}=="6860"
ATTR{idProduct}=="6866"
ATTR{idProduct}=="9011"
ATTR{idProduct}=="9039"
ATTR{idProduct}=="904e"
ATTR{idProduct}=="90bb"
ATTR{idProduct}=="ff48"
``` 
...and then checked each one separately so that the matches belong to one common `ATTR{idVendor}!=`...

Here's what I caught:
```
#	HTC
ATTR{idVendor}!="0bb4", GOTO="not_HTC"
...
#		Desire Z
ATTR{idProduct}=="0c91", ENV{adb_adbfast}="yes"
...
#		Vision
ATTR{idProduct}=="0c91", SYMLINK+="android_adb"
```
```
#	Huawei
ATTR{idVendor}!="12d1", GOTO="not_Huawei"
...
#		P10 Lite
ATTR{idProduct}=="107e", SYMLINK+="android_adb"
...
...
#		Mate 9
ATTR{idProduct}=="107e", SYMLINK+="android_adb"
```
```
#	LG
ATTR{idVendor}!="1004", GOTO="not_LG"
...
#		Optimus LTE
...
ATTR{idProduct}=="61f9", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"
...
#		4X HD P880
ATTR{idProduct}=="61f9", SYMLINK+="android_adb"
```
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
#		Galaxy i5800 (681c=debug,6601=fastboot,68a0=mediaplayer)
...
ATTR{idProduct}=="6601", SYMLINK+="android_fastboot"
...
#		Galaxy i9000 S, i9300 S3
ATTR{idProduct}=="6601", SYMLINK+="android_adb"
```
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
#		Galaxy i5700
ATTR{idProduct}=="681c", ENV{adb_adbfast}="yes"
#		Galaxy i5800 (681c=debug,6601=fastboot,68a0=mediaplayer)
ATTR{idProduct}=="681c", SYMLINK+="android_adb"
```
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
#		Galaxy i9000 S, i9300 S3
...
ATTR{idProduct}=="685d", MODE="0660"
...
#		Galaxy S4 GT-I9500
ATTR{idProduct}=="685d", SYMLINK+="android_adb"
```
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
#		Galaxy Nexus (GSM) (6860=mtp,adb 6864=rndis,adb 6866=ptp,adb)
ATTR{idProduct}=="6860", SYMLINK+="android_adb"
...
#		Galaxy Core, Tab 10.1, i9100 S2, i9300 S3, N5100 Note (8.0), Galaxy S3 SHW-M440S 3G (Korea only)
ATTR{idProduct}=="6860", SYMLINK+="android_adb"
```
```
#	Samsung
ATTR{idVendor}!="04e8", GOTO="not_Samsung"
...
#		Galaxy Nexus (GSM) (6860=mtp,adb 6864=rndis,adb 6866=ptp,adb)
...
ATTR{idProduct}=="6866", SYMLINK+="android_adb"
...
#		Galaxy i9300 S3
ATTR{idProduct}=="6866", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"
```
```
#	XiaoMi
ATTR{idVendor}!="2717", GOTO="not_XiaoMi"
...
#		Mi Mix / A1 (ff88=rndis+adb, ff18=ptp+adb, ff48=mtp+adb, ff28=storage+adb)
...
ATTR{idProduct}=="ff48", SYMLINK+="android_adb"
...
#		RedMi 8 Pro
ATTR{idProduct}=="ff48", SYMLINK+="android_adb"
```

I don't know if you need it, but I still had nothing to do. I hope it will come in handy... :)

p.s. This is not an error, so I did not create a separate topic.

Sincerely,
Alex

**Comment by M0Rf30** [comment]
Yeah I noticed other duplicates, and I would like to remove them, but the fact is that I can test them on a so wide list of devices.
To be more clear: some of them have the same productid but they report different envs (adb or fast for example). I also reported @JoesCat findings [here](https://github.com/M0Rf30/android-udev-rules/wiki). But how to be sure that nothing will break? We can approach it, generalizing the ones that report same id and fast and adb using fast (enabling both the modes). I have to think about it more deeply. Thanks for your efforts. Please feel free to elaborate more
