### ISSUE TITLE
Xiaomi Mi A1

### ISSUE THREAD

**Issue by jendrikw** [M0Rf30/android-udev-rules#221]
This phone reports idVendor and idProduct as 0000, so I use `ATTR{manufacturer}=="Xiaomi", ATTR{product}=="Mi A1"`

**Comment by JoesCat** [comment]
MiA1 will not work.

Inventing values also does not help anyone.

How/where did you get this phone?
That seems to be some sort of custom or modified firmware.

**Comment by JoesCat** [comment]
LOL - that makes sense.
Your phone is physically a Xiaomi, however, the operating system you have is not put together by Xiaomi. It appears the values are simply left as 0000 and 0000.

For this unique situation, you may simply want to have a separate line near the top, right after LABEL="android_usb_rules_begin"
which looks lik this:
`---
ATTR{idVendor}=="0000", ATTR{idProduct}=="0000", ENV{adb_adb}="yes", GOTO="android_usb_rule_match"
`---

hopefully I didn't add any typing errors above.

**Comment by tomer-1** [comment]
@jendrikw you bought a Xiaomi Mi A1 with Lineage OS 16 pre-installed?

**Comment by jendrikw** [comment]
No, I flashed it myself

**Comment by tomer-1** [comment]
i don't think that it's supposed to change the device vendor and product ID..
