### ISSUE TITLE
OnePlus 8t

### ISSUE THREAD

**Issue by DrymarchonShaun** [M0Rf30/android-udev-rules#240]
I'm not 100% sure how to go about adding these to the repo correctly, but i have a list of VendorIDs/ProductIDs for the oneplus 8t, listed below.

```Charging / Charging + MTP - 22d9:2764

Sideload       - 2a70:d001

Recovery       - 2a70:9012

PTP            - 22d9:2771

Debug + PTP    - 22d9:2772

Debug + MTP    - 22d9:2765

Debug          - 22d9:2769

Bootloader     - 18d1:d00d```

**Comment by JoesCat** [comment]
18d1:d00d is already covered in the google phone section here, no need to repeat it:
```
189: #   Recovery adb entry for Nexus Family (orig d001, OP3 has 18d1:d002)
190: ATTR{idProduct}=="d00?", ENV{adb_adb}="yes"
191: #   Generic and unspecified debug interface (test after d00?)
192: ATTR{idProduct}=="d00d", ENV{adb_adbfast}="yes"
```

22d9:.... should be covered in the # Oppo area.
22d9:2769 is already covered.
Add lines for:
```
#   OnePlus 8T (22d9:2771=adb,PTP, 22d9:2772=adb,MTP)
ATTR{idProduct}=="2771", ENV{adb_adb}="yes"
ATTR{idProduct}=="2772", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"
```

PTP 22d9:2771 doesn't use debug, ideally, it belongs to a PTP library

Both 2a70:.... would belong in the OnePlus(Oreo) area - approx at lines 463...471

Your list appears to hit three different vendors (2a70, 22d9, 18d1). 18d1 is understandable, but I'm a little curious why 2 other vendors (I only expected only 1).

**Comment by DrymarchonShaun** [comment]
I believe there was a merge of sorts between Oppo and Oneplus recently-ish

**Comment by JoesCat** [comment]
That seems to make sense. Curious why they decided to keep both vendor values in the same phone.....maybe backwards compatibility?

looking at your values of PTP, and Debug+PTP, I think android rules probably needs some improving. Since you posted Debug+MTP, do you also have a value for just MTP ?

**Comment by DrymarchonShaun** [comment]
I'll have to double-check, but I think it was the same as debug+mtp.
