### ISSUE TITLE
Motorola Moto E22i

### ISSUE THREAD

**Issue by alpenb** [M0Rf30/android-udev-rules#259]
```
lsusb
Bus 005 Device 003: ID 0e8d:201c MediaTek Inc. moto e22i
```
Seems the same as 
https://github.com/M0Rf30/android-udev-rules/commit/e8b25b1beb231640094683786dd7a1495d50aee5

**Comment by JoesCat** [comment]
Doing some searching....found this:
https://www.google.com/search?q=motorola+mediateck
https://www.tomsguide.com/opinion/motorola-mediatek

**Comment by JoesCat** [comment]
In Settings->Developer_options:
can you cycle through the various combinations of:
Debugging USB debugging
and
Select USB Configuration (charging, MTP, PTP,RNDIS,Audio,Midi)
so that we have the various values available.

I'm assuming the menu is similar to another motorola phone I have temp access to.

**Comment by alpenb** [comment]
No data transfer
`Bus 005 Device 047: ID 0e8d:201c MediaTek Inc. moto e22i
`
PTP
`Bus 005 Device 048: ID 0e8d:200c MediaTek Inc. moto e22i
`
Midi
`Bus 005 Device 049: ID 0e8d:2048 MediaTek Inc. moto e22i
`
USB-tethering
`Bus 005 Device 050: ID 0e8d:2005 MediaTek Inc. moto e22i
`
File transfer
`Bus 005 Device 051: ID 0e8d:201d MediaTek Inc. moto e22i
`
![motoE22i](https://github.com/M0Rf30/android-udev-rules/assets/120461022/85993e9e-79e9-4015-8e09-27213be52f4c)

**Comment by JoesCat** [comment]
Looks good, but we're half-way there.
Missing developer mode on....or off?
I'm guessing from the lack of developer-mode, you did not see a setting for that? and these values are for developer mode off?

Doing a quick search I found this, to turn-on [developer mode.](https://en-us.support.motorola.com/app/answers/detail/a_id/160067/~/developer-options)
Where are the developer options on my phone ?
1. Go to Settings > System.
2. Touch About phone.
3. Touch the Build number field 7 times. You will begin seeing a message as you approach the 7 touches.
4. Touch the back arrow once complete, and Developer options will now appear under Settings.
Use a little caution when toggling modes, it may switch to default modes while trying.
Thanks for the first set of values - that was very helpful.

**Comment by alpenb** [comment]
This was in the dev mode. What else should show up?

**Comment by JoesCat** [comment]
Ok, I was not sure if it was in developer mode or not. so these values are basically
```c
No data transfer+debug
Bus 005 Device 047: ID 0e8d:201c MediaTek Inc. moto e22i 
PTP+debug
Bus 005 Device 048: ID 0e8d:200c MediaTek Inc. moto e22i 
Midi+debug
Bus 005 Device 049: ID 0e8d:2048 MediaTek Inc. moto e22i 
USB-tethering+debug
Bus 005 Device 050: ID 0e8d:2005 MediaTek Inc. moto e22i 
File transfer+debug
```

Can you try again with usb debug turned off?
There should be another set of values - this should help get details on all the modes.
You might need to turn-on/off usb debug as you go through each mode. I noticed this quirk with another phone.

**Comment by M0Rf30** [comment]
Closed by
https://github.com/M0Rf30/android-udev-rules/commit/d9022cd3bee3f8e31261968380a35bf924ae1042
