### ISSUE TITLE
Does not work on fedora 

### ISSUE THREAD

**Issue by DiamivaeBro** [M0Rf30/android-udev-rules#261]
Script run without any errors but adb still not work 
Fedora 38

**Comment by M0Rf30** [comment]
Hi, any log? How do you installed it? if with script can you post the content of a 
```
bash -x install.sh
```
with admin privileges?

**Comment by DiamivaeBro** [comment]
All good now,i just manually add user to the adbusers using 
`
sudo usermod -aG adbusers $Username
`
