### ISSUE TITLE
Meizu M6T

### ISSUE THREAD

**Issue by mskiptr** [M0Rf30/android-udev-rules#262]
Back in November I was helping a friend remove some manufacturer bloatware from her phone. Since the USB device didn't have the right permissions set for ADB to work automatically, I noted down the USB ids with a plan to one day contribute this data upstream.
```
Bus 001 Device 101: ID 2a45:201c Meizu Corp. M6T
```

This day would be today, but looking at other submissions I guess I should probably gather a more comprehensive list – for different connection modes and whatnot.

For now this is all I've got. If it's already useful I can try preparing a PR.

**Comment by JoesCat** [comment]
Hi Piotr,Android Developers tend to have a better grasp of these details so yes, having the other info is also going to be helpful for the 99% who are users transferring files, pictures etc. Those details can be shared with the other projects like MTP, cameras, tethering, audio, etc.Go ahead with this PR and later you can add the other details that can be shared.

**Comment by mskiptr** [comment]
#263 has landed. And with that, this issue can be closed.
