### ISSUE TITLE
Samsung Galaxy s24 not detected

### ISSUE THREAD

**Issue by TukanDev** [M0Rf30/android-udev-rules#310]
Hello,
Recently i bought samsung galaxy s24 and i noticed its not recognized at all on entire system even in `lsusb` it does not even charge nor wants to be detected for any file transfer, due to that i am even unable to write my own udev rule for it as i can not pick vendor and product id.
And yes my cable is not broken before somebody asks haha.
I am sadly not able to provide much info besides this.
As readme states on arch you dont need anything special it seems in this case its needed... as my samsung s21 is detected fine from the beggining.

Edit:
OS: Arch Linux x86_64
DE: KDE Plasma 5.27.10

**Comment by JoesCat** [comment]
> it does not even charge

You might be trying to pull more power than the USB port is capable of serving, which may mean the USB port turns itself off to prevent overheating and/or burnout.
USB ports with high power ratings will have a [colour](https://www.google.com/search?q=usb+colour+code) like blue or orange (desktop PC).
For a laptop, you will probably be limited to the C connector on it if it has one, or maybe an external hub that gives enough power.

If the S24 can charge from the USB connector, you are one step closer.
If the USB cable (or connectors) gets warm, replace the cable.

**Comment by TukanDev** [comment]
> > it does not even charge
> 
> You might be trying to pull more power than the USB port is capable of serving, which may mean the USB port turns itself off to prevent overheating and/or burnout. USB ports with high power ratings will have a [colour](https://www.google.com/search?q=usb+colour+code) like blue or orange (desktop PC). For a laptop, you will probably be limited to the C connector on it if it has one, or maybe an external hub that gives enough power.
> 
> If the S24 can charge from the USB connector, you are one step closer. If the USB cable (or connectors) gets warm, replace the cable.
> 
> [another reference](https://www.reddit.com/r/samsung/comments/1aclywx/s24_ultra_broken_charging_port/?rdt=35445)

That's the thing it charges with normal charging thru wall socket, but thru usb c on my laptop it does not, the charging isn't even the major issue i can live with that not functioning haha the thing is due to it not being detected at all i cant even adb the device which is something i would highly appreciate if i could...
I can confirm cable i am using is fine as it is fresh new one from the package. I inspected a cable and connector they don't get hot at all (at least not immediately) i will need to see about that possibility in bit more of a detail and definitely take look at a manual of my laptop to see if it has mention of usb c connector power output and limit. Will give reddit thread a read.

**Comment by JoesCat** [comment]
The laptop is doing the right thing, which is to self-protect the USB port. I think you'd prefer it to shutdown, vs having a dead USB port. The laptop does not have enough power to charge your phone, and therefore simply shuts down the port. communications too. This is why you see no communications, including no lsusb detection.

A fresh USB cable from the package is not what I mean. Being fresh is not the same as being capable of supplying the required power. Cheap USB cables tend to cut costs, and that means thin wire, poor connectors, these tend to warm-up and in some cases can be a fire hazard. For your S24, you need to make sure the USB cable is rated to do the job of supplying power. Use the USB cable that came with the phone, or buy the cable from a reputable store that knows electronics and phones - you don't want to be causing a home fire.

I have not tested this, but it is likely that - In terms of the laptop, you may have to use a docking station - these are often powered from a wall adapter and likely have the high-powered USB connectors too.

Another possibility you might want to try, is the opposite direction (going retro) and try an older 4pin (black tongue) USB cord, or an older 4pin (black tongue) USB hub (if you have one). The phone can only talk on 2pins, therefore may realize it cannot (or should not attempt to fast-charge). I have tried a relatively new phone similar to the S24 this way, and note the charge time as something horrible like 12+ hours, but the USB port stays alive, and it does maintain a connection. If you have a monitor with a USB mini-hub (likely 2 USB connections on it), you may want to try connecting from laptop USB, to monitor USB, and from monitor to phone - might be worth a try.

Last thought, try charge phone to 100%, then when it is fully charged, try the laptop again? You won't be talking for long before the phone wants to top-up again. Don't know if it will work, but could give it a try.

**Comment by TukanDev** [comment]
I am very glad its shutting itself down in fact, dont get me wrong. My intention isnt to force it and cause a hazard or anything, i very well understand if it doesnt supply enough power to leave it be and find a solution after your first comment haha. I never even thought of power output being an issue here but your analysis really makes sense. I will try that full charged trick doubt it will work but i will look for solution, considering i am in fact using cable that came packaged with a phone. Thanks again i will mark this as closed when i get on pc.On Feb 10, 2024 05:20, Joe ***@***.***> wrote:
The laptop is doing the right thing, which is to self-protect the USB port. I think you'd prefer it to shutdown, vs having a dead USB port. The laptop does not have enough power to charge your phone, and therefore simply shuts down the port. communications too. This is why you see no communications, including no lsusb detection.
A fresh USB cable from the package is not what I mean. Being fresh is not the same as being capable of supplying the required power. Cheap USB cables tend to cut costs, and that means thin wire, poor connectors, these tend to warm-up and in some cases can be a fire hazard. For your S24, you need to make sure the USB cable is rated to do the job of supplying power. Use the USB cable that came with the phone, or buy the cable from a reputable store that knows electronics and phones - you don't want to be causing a home fire.
I have not tested this, but it is likely that - In terms of the laptop, you may have to use a docking station - these are often powered from a wall adapter and likely have the high-powered USB connectors too.
Another possibility you might want to try, is the opposite direction (going retro) and try an older 4pin (black tongue) USB cord, or an older 4pin (black tongue) USB hub (if you have one). The phone can only talk on 2pins, therefore may realize it cannot (or should not attempt to fast-charge). I have tried a relatively new phone similar to the S24 this way, and note the charge time as something horrible like 12+ hours, but the USB port stays alive, and it does maintain a connection. If you have a monitor with a USB mini-hub (likely 2 USB connections on it), you may want to try connecting from laptop USB, to monitor USB, and from monitor to phone - might be worth a try.
Last thought, try charge phone to 100%, then when it is fully charged, try the laptop again? You won't be talking for long before the phone wants to top-up again. Don't know if it will work, but could give it a try.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/M0Rf30/android-udev-rules/issues/310#issuecomment-1936854154",
"url": "https://github.com/M0Rf30/android-udev-rules/issues/310#issuecomment-1936854154",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JoesCat** [comment]
Looking forward to seeing you resolve this. Whatever you find will help anyone else reading this running into similar problems. :-)

After the problem is resolved: When you get the S24 recognized, I'm guessing it will have similar idVendor:idProduct values listed here for the Samsungs - this seems to be a smart thing Samsung did, and we've seen it also with some other vendors like the latest Motorolas (repeating codes between various phones). In any case, please go through the codes and report back. It is still worth sharing the info, even if it is basically a "Me-too" set of values. Your info could be shared elsewhere, like here, libusb, and other projects (see issue #269 as a detailed example).

**Comment by TukanDev** [comment]
> Looking forward to seeing you resolve this. Whatever you find will help anyone else reading this running into similar problems. :-)
> 
> After the problem is resolved: When you get the S24 recognized, I'm guessing it will have similar idVendor:idProduct values listed here for the Samsungs - this seems to be a smart thing Samsung did, and we've seen it also with some other vendors like the latest Motorolas (repeating codes between various phones). In any case, please go through the codes and report back. It is still worth sharing the info, even if it is basically a "Me-too" set of values. Your info could be shared elsewhere, like here, libusb, and other projects (see issue #269 as a detailed example).

Found the fix connected it to usb A to usb c cable i dug up from somewhere and it worked i managed to debloat my phone and charging works guess my usb c on a laptop isnt meant for that high power.
Will check to make a report on libusb repository as a reference for them too.

As for the ids (ids are same regardless of usb debugging being enabled or not):
idVendor: 04e8
idProduct: 6860
Recognized as: Samsung Electronics Co., Ltd Galaxy series, misc. (MTP mode)

I will leave this open for a bit in case you or anyone else wants to add something. Will for sure close it tomorrow if nothing else needs adding to this issue.
