### ISSUE TITLE
unauthorized device (Android Recovery) even after updating the rules and replugging the USB cable

### ISSUE THREAD

**Issue by Umeaboy** [M0Rf30/android-udev-rules#312]
I followed the instructions from the readme file here and got no issues until I replugged the cable and ran adb devices.

heimdall detects the phone just fine.

**Comment by Umeaboy** [comment]
This is a Samsung Galaxy S21 5G (G991B/DS), exynos based.
Bootloader is unlocked.

**Comment by JoesCat** [comment]
Did you install a custom ROM? or are you using the Samsung ROM?

**Comment by Umeaboy** [comment]
I used to be rooted, but went back to stock rom since there was no .zip for lineage built at that time.
/Kristoffer

9 mars 2024 08:16 av ***@***.***:

**Comment by SalvatoreNoschese** [comment]
Check with lsusb and put here output.

**Comment by bahramiholding** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
izzley, @Thammada, @pacman255, @trumhemcut, @mvillena3, @Holovin, @geoffclapp, @setchy, @hassansallam, @gdlafferty, @arkadiyg, @fshot, @anatolinicolae, @rcho, @Tenclea, @bbrod, @Astrogeorgeonethree, @0xAbdoAli, @ninjarz, @marcusficner
