### ISSUE TITLE
Please add udev for Moto G54

### ISSUE THREAD

**Issue by Ravi-Kishor** [M0Rf30/android-udev-rules#315]
lsusb output is

Bus 003 Device 003: ID 22b8:2e81 Motorola PCS moto g54 5G

**Comment by JoesCat** [comment]
Thanks @Ravi-Kishor ,
Already included at approx line [530](https://github.com/M0Rf30/android-udev-rules/blob/main/51-android.rules):
```
ATTR{idProduct}=="2e80", GOTO="adbfast"
ATTR{idProduct}=="2e81", GOTO="adb"
ATTR{idProduct}=="2e84", GOTO="adbptp"
```

Assumming you are in adb/developer mode?
