### ISSUE TITLE
install.sh does not work on fedora

### ISSUE THREAD

**Issue by jangorecki** [M0Rf30/android-udev-rules#326]
```sh
sudo bash -x install.sh
+ $'\r'
install.sh: line 2: $'\r': command not found
++ id -u
+ CURRENT_UID=$'0\r'
+ $'\r'
install.sh: line 4: $'\r': command not found
install.sh: line 35: syntax error: unexpected end of file
```
Fedora Linux 39

**Comment by M0Rf30** [comment]
can't reproduce.
I tried on fedora 39.
Maybe you messed up your environment?
seems like every new line is interpreted as `$'\r'`. Used any windows environment?
try with `dos2unix install.sh` and retry.

**Comment by JoesCat** [comment]
Hi @jangorecki  - Tidbit of Trivia:
```
Newline on linux is '/n'
Newline on (older) MACs is '/r' - newer MACs now use '/n' too
Newline on Windows is '/r/n'
```
You can see where there's an '/r' now.

I think some windows git installations might also add/remove '/r' to make text files compatible with plain text editors like NOTEPAD.EXE.

It might be worth inspecting your git setup.

**Comment by jangorecki** [comment]
That is possible that I mess up some git config trying to work on windows originated git repository. I checked options and I see `core.autocrlf=true`. Will try to reset that to default.

**Comment by jangorecki** [comment]
issue is resolved, thanks for the tips.
```sh
git config --list --show-origin | grep core.autocrlf
```
this told me where autocrlf was set (.gitconfig)
and then removing that setting made the install script not to error anymore.
