### ISSUE TITLE
What is needed to reenable Nook?

### ISSUE THREAD

**Issue by rkjnsn** [M0Rf30/android-udev-rules#334]
I notice that the entry for the Barnes & Noble Nook is currently comment out with the note "Need product specific rules". Do you just need product IDs for the various Nooks?

If it helps, I have a Nook Glowlight 3, which shows up as

    ID 2080:000b Barnes & Noble BNRV520 [Nook Glowlight 3]

**Comment by M0Rf30** [comment]
Please let me know if 
https://github.com/M0Rf30/android-udev-rules/commit/48f182fc316fd8efc4f41a4eb5e48a38070cd557

works for your device

**Comment by rkjnsn** [comment]
That appears to work for me, thanks!
