### ISSUE TITLE
HTC gets excluded by alleged check "if debug mode is off" rule

### ISSUE THREAD

**Issue by dvzrv** [M0Rf30/android-udev-rules#55]
With the rules "as is" I can not use my HTC One S.
The idProduct 0ff9 is the said mobile, as you can see here (from lsusb):
  ID 0bb4:0ff9 HTC (High Tech Computer Corp.) Desire / Desire HD / Hero / Thunderbolt (Charge Mode)

After making these changes, I can use adb on the phone again (as it now properly gets recognized).
https://github.com/dvzrv/android-udev-rules/commit/f23cead4019dccf5822ce61f2d7918fd18731873

**Comment by M0Rf30** [comment]
Thanks
