### ISSUE TITLE
possible bug with phone compatibility. 

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [M0Rf30/android-udev-rules#58]
This all started because I could not get my LG G2(rogers) android phone to appear in thunar when I plugged it in. The phone was in MTP mode. Kernel is x86_64 Linux 4.1.5-1-ARCH, running XFCE 4.12.

libmtp, gvfs-mtp, and android-udev were installed. I later tried installing android-udev-git from the AUR and still had no joy. At that point I went to terminal and typed mtp-detect, then mtp-connect and found out my phone had these identifiers (VID=1004 and PID=631c). 

I went to /usr/lib/udev/rules.d/51-android.rules and saw that although my phone was listed, the info didn't match up, likely due to different variants of a phone being released in different locations. 

Under the LG header, I found this

    ATTR{idProduct}=="618e", SYMLINK+="android_adb"
    #               G2 D803

So I added a line underneath with the edited PID found above, and changed the product identifier below so I'd know it apart from the original.

    ATTR{idProduct}=="618c", SYMLINK+="android_adb"
    #               G2 D803 rogers

I saved the file, disconnected my phone, rebooted, reconnected the phone and it all worked! 

android-udev is the community based file. I had not edited any file with this. This fix was only done with android-udev-git from the AUR and is working. I will be testing this on a NOTE2 when my spouse gets home.

**Comment by parkerlreed** [comment]
Just a note: udev rules take effect immediately. You don't have to reboot. They get read as a device is plugged in. Glad you solved your issue and I hope this gets merge upstream.
