### ISSUE TITLE
Add comment #HTC Sensation for usb id 0bb4:0f87

### ISSUE THREAD

**Issue by gojun077** [M0Rf30/android-udev-rules#63]
I have a one-line change I'd like to add to `51-android.rules`, but for such a small change I don't know if it is necessary to fork the entire project and submit a pull request.

For `ATTR{idVendor}!="0bb4"` (HTC) the device id `0f87` belongs to the HTC Sensation. I would like to add this comment before **line 158** in `51-android.rules`:

    #		Sensation
    ATTR{idProduct}=="0f87", SYMLINK+="android_adb"

M0Rf30, could you do this for me, or should I just fork and submit a pull request?

Thanks,
Jun

**Comment by M0Rf30** [comment]
This is a community archive of rules. Please fork and pull request. Your contribution will be visible on the commit log :dancers:
