### ISSUE TITLE
Possible cleanup needed for second instance of ATTR{idProduct}=="6860"

### ISSUE THREAD

**Issue by gojun077** [M0Rf30/android-udev-rules#67]
Hi M0Rf30~

I recently submitted a pull request adding a comment line for `ATTR{idProduct}=="6860"`
(*Samsung Galaxy S3 SHW-M440S 3G for Korea*). Just below this line, however, are another
two lines with the same ATTR. I think it is an old placeholder. Also, *i9300 S3* is already listed
under `ATTR 6601` a few lines above. Are the two lines below OK to delete?

    #               Galaxy Core, Tab 10.1, i9100 S2, i9300 S3, N5100 Note (8.0)
    ATTR{idProduct}=="6860"

Thanks,
-Jun

**Comment by M0Rf30** [comment]
yes, please do a pull request and I'll merge your contribution
