### ISSUE TITLE
Rules too broad for Asus; catching my bluetooth dongle.

### ISSUE THREAD

**Issue by ntzrmtthihu777** [M0Rf30/android-udev-rules#72]
As titled. The rules are too broad and catch my
`0b05:17cb ASUSTek Computer, Inc. Broadcom BCM20702A0 Bluetooth` dongle:

    ls -l /dev/bus/usb/006/
    total 0
    crw-rw-r--  1 root root     189, 640 Jan 20 19:19 001
    crw-rw----+ 1 root adbusers 189, 641 Jan 20 19:19 002
    crw-rw-r--  1 root root     189, 643 Jan 20 19:19 004

No harm being done as far as I can tell, but I thought you'd like to know.

**Comment by M0Rf30** [comment]
fixed by JoesCat. Thank you
