### ISSUE TITLE
Fix documentation in README for udev setup

### ISSUE THREAD

**Issue by truedat101** [M0Rf30/android-udev-rules#84]
sudo ln -s `pwd`/51-android.rules /etc/udev/rules.d/

works.  If you do the relative path, the softlink is dangling.

**Comment by M0Rf30** [comment]
solved. Thanks man

**Comment by truedat101** [comment]
That rules.  Also, I'll add another item for Nexus 5 (apparently there's another possible usb identifier, maybe for a different market).
