### ISSUE TITLE
Unavoidable GOTO

### ISSUE THREAD

**Issue by tibocapo** [M0Rf30/android-udev-rules#88]
It seems this GOTO force the script to skip everything after it.
Did I understand something wrong ?

`#		D70e`
`ATTR{idProduct}=="0ba3", SYMLINK+="android_adb"`
`GOTO="android_usb_rule_match"`

**Comment by zamber** [comment]
That's right.

https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules#L496 :

    # Skip other vendor tests
    LABEL="android_usb_rule_match"

**Comment by tibocapo** [comment]
My issue is my vendor id is never matched because of this row:

https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules#L132

I have an HTC which is supposed to be check after this GOTO.

**Comment by zamber** [comment]
I see, this should be fixed. I'll do a Pull request later today if I find a free minute. For now just change it from:
```
#	Honeywell/Foxconn
ATTR{idVendor}=="0c2e", ENV{adb_user}="yes"
#		D70e
ATTR{idProduct}=="0ba3", SYMLINK+="android_adb"
GOTO="android_usb_rule_match"
```
to:
```
#	Honeywell/Foxconn
ATTR{idVendor}!="0c2e", GOTO="not_Foxconn"
ENV{adb_user}="yes"
#		D70e
ATTR{idProduct}=="0ba3", SYMLINK+="android_adb"
GOTO="android_usb_rule_match"
LABEL="not_Foxconn"
```
and it should work fine.

**Comment by tibocapo** [comment]
Thanks

**Comment by zamber** [comment]
You're welcome :). Thanks for taking your time to get an account on GitHub
to report this!
